---
- name: Configure BIG-IP
  hosts: bigip1
  connection: local

  roles:
    - role: apply_initial_configuration
      tags: [initial_configuration]

    - role: configure_load_balancing
      tags: [load_balancing]
