---
- name: Remove Virtual Servers
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ virtual_servers }}"

- name: Remove source address persistence profile
  f5networks.f5_modules.bigip_profile_persistence_src_addr:
    provider: "{{ provider }}"
    name: "{{ source_address_persistence_profile }}"
    state: absent

- name: Remove pools
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    lb_method: "{{ item.lb_method }}"
    monitors: "{{ item.monitors }}"
    state: absent
  loop: "{{ pools }}"

- name: Remove custom http monitor
  f5networks.f5_modules.bigip_monitor_http:
    provider: "{{ provider }}"
    name: "{{ monitor }}"
    state: absent

- name: Remove nodes
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    name: "{{ item.member_name }}"
    state: absent
  loop: "{{ pool_members }}"
