---
- name: Configure system
  ansible.builtin.include_tasks: configure_system.yml

- name: Configure network
  ansible.builtin.include_tasks: configure_network.yml

- name: Save BIG-IP running configuration
  f5networks.f5_modules.bigip_config:
    provider: "{{ provider }}"
    save: true
